############################
## Navbar
############################

main:
- name: Science
  url: /science
  weight: 2
- name: SciCom
  url: /scicom
  weight: 3
- name: Blog
  url: /blog/
  weight: 4
- name: CV
  url: /cv/
  weight: 5
- name: About
  url: /about/
  weight: 6
